### ISSUE TITLE
Typo adds has_sync_disabled items to sync_enabled list

### ISSUE THREAD

**Issue by mauritsvanrees** [collective/collective.contentsync2#1]
I am just looking through the code to see how this package works, and I spot what seems to be an error.
These [lines in `sync_assignments.py`](https://github.com/collective/collective.contentsync2/blob/master/src/collective/contentsync/sync/sync_assignments.py#L22-L26) iterate over brains with `has_sync_disabled=True` and mistakenly add them to the result in `sync_enabled`, which should be `sync_disabled`.

**Comment by zopyx** [comment]
FIxed
